CNMWebApp/Controllers/SolicitudController.cs
using CNMWebApp.Authorization;
using CNMWebApp.Models;
using CNMWebApp.Services;
using Microsoft.AspNet.Identity;
using PagedList;
using Rotativa.Options;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CNMWebApp.Controllers
{
    [Auth(Roles = "Funcionario, Director, Jefatura, Recursos Humanos, Manager")]
    public class SolicitudController : Controller
    {
        private SolicitudService solicitudService;
        private UserService userService;
        private EmailNotificationService emailNotification;
        private RoleService roleService;

        public SolicitudController()
        {
            solicitudService = new SolicitudService();
            userService = new UserService();
            emailNotification = new EmailNotificationService();
            roleService = new RoleService();
        }

        // GET: Solicitud
        public async Task<ActionResult> Index(string filtro, int? pagina, string filtrarPor, string fechaInicio, string fechaFinal)
        {
            ViewBag.FiltradoPor = filtrarPor;
            ViewBag.FechaInicio = fechaInicio;
            ViewBag.FechaFinal = fechaFinal;

            var user = await userService.GetLoggedInUser();
            if (user == null)
                return RedirectToAction("LogOut", "Account");

            try
            {
                var solicitudes = ObtenerSolicitudesPorFiltro(filtrarPor, user, fechaInicio, fechaFinal);

                if (!string.IsNullOrEmpty(filtro))
                {
                    solicitudes = FiltrarSolicitudes(solicitudes, filtro);
                }

                var solicitudesMostrar = solicitudes.Select(x => new SolicitudViewModel()
                {
                    CantidadDiasSolicitados = x.CantidadDiasSolicitados,
                    Comentario = x.Comentario,
                    FechaSolicitud = x.FechaSolicitud,
                    Id = x.UsuarioId,
                    SolicitudId = x.SolicitudVacacionesId,
                    Nombre = x.Usuario.Nombre,
                    PrimerApellido = x.Usuario.PrimerApellido,
                    SegundoApellido = x.Usuario.SegundoApellido,
                    Estado = x.Estado.Nombre
                }).ToList();

                int tamanoPagina = 10;
                int numeroPagina = (pagina ?? 1);

                return View(solicitudesMostrar.ToPagedList(numeroPagina, tamanoPagina));
            }
            catch(Exception ex)
            {
                if (ex.Message.Equals("Rol inválido"))
                    return View("~/Views/Shared/Unauthorized.cshtml");
            }

            return View(new List<SolicitudVacaciones>());
        }

        private IEnumerable<SolicitudVacaciones> ObtenerSolicitudesPorFiltro(string filtrarPor, UserViewModel user, string fechaInicio, string fechaFinal)
        {
            if (filtrarPor == null)
                return solicitudService.ObtenerMisSolicitudes(user, fechaInicio, fechaFinal).ToList();
            if (filtrarPor.Equals("funcionarios", StringComparison.OrdinalIgnoreCase))
            {
                if (!(user.Role.Name.Equals("funcionario", StringComparison.OrdinalIgnoreCase) && user.EsSuperusuario) && 
                    !(user.Role.Name.Equals("director", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("recursos humanos", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("manager", StringComparison.OrdinalIgnoreCase)))
                    throw new Exception("Rol inválido");
                    
                return solicitudService.ObtenerSolicitudesFuncionarios(fechaInicio, fechaFinal).ToList();
            }
                
            if (filtrarPor.Equals("funcionariosporunidadtecnica", StringComparison.OrdinalIgnoreCase))
            {
                // El rol de funcionario es el unico que no puede ver 
                // solicitudes de funcionarios dentro de una unidad tecnica especifica

                if(!(user.Role.Name.Equals("funcionario", StringComparison.OrdinalIgnoreCase) && user.EsSuperusuario) && 
                    user.Role.Name.Equals("funcionario", StringComparison.OrdinalIgnoreCase))
                    throw new Exception("Rol inválido");

                return solicitudService.ObtenerSolicitudesFuncionariosPorUnidad(fechaInicio, fechaFinal, user).ToList();
            }
                
            if (filtrarPor.Equals("jefaturas", StringComparison.OrdinalIgnoreCase))
            {
                if (!(user.Role.Name.Equals("funcionario", StringComparison.OrdinalIgnoreCase) && user.EsSuperusuario) && 
                    !(user.Role.Name.Equals("director", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("recursos humanos", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("manager", StringComparison.OrdinalIgnoreCase)))
                    throw new Exception("Rol inválido");

                return solicitudService.ObtenerSolicitudesJefaturas(fechaInicio, fechaFinal).ToList();
            }
                
            if (filtrarPor.Equals("recursoshumanos", StringComparison.OrdinalIgnoreCase))
            {
                if (!(user.Role.Name.Equals("funcionario", StringComparison.OrdinalIgnoreCase) && user.EsSuperusuario) && 
                    !(user.Role.Name.Equals("director", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("recursos humanos", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("manager", StringComparison.OrdinalIgnoreCase)))
                    throw new Exception("Rol inválido");

                return solicitudService.ObtenerSolicitudesRH(fechaInicio, fechaFinal).ToList();
            }
                
            if (filtrarPor.Equals("directorgeneral", StringComparison.OrdinalIgnoreCase))
            {
                if (!(user.Role.Name.Equals("funcionario", StringComparison.OrdinalIgnoreCase) && user.EsSuperusuario) && 
                    !(user.Role.Name.Equals("director", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("recursos humanos", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("manager", StringComparison.OrdinalIgnoreCase)))
                    throw new Exception("Rol inválido");

                return solicitudService.ObtenerSolicitudesDirectorGeneral(fechaInicio, fechaFinal).ToList();
            }
                
            if (filtrarPor.Equals("directoradministrativo", StringComparison.OrdinalIgnoreCase))
            {
                if (!(user.Role.Name.Equals("funcionario", StringComparison.OrdinalIgnoreCase) && user.EsSuperusuario) && 
                    !(user.Role.Name.Equals("director", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("recursos humanos", StringComparison.OrdinalIgnoreCase) ||
                    user.Role.Name.Equals("manager", StringComparison.OrdinalIgnoreCase)))
                    throw new Exception("Rol inválido");

                return solicitudService.ObtenerSolicitudesDirectorAdministrativo(fechaInicio, fechaFinal).ToList();
            }
                
            if (filtrarPor.Equals("todos", StringComparison.OrdinalIgnoreCase))
                return solicitudService.ObtenerTodasSolicitudesPorRol(fechaInicio, fechaFinal, user).ToList();

            return solicitudService.ObtenerMisSolicitudes(user, fechaInicio, fechaFinal);
        }

        // GET Solicitud/Detalle/1
        public ActionResult Detalle(int id)
        {
            var solicitud = solicitudService.ObtenerSolicitudPorId(id);
            if (solicitud == null)
                return HttpNotFound("ID de solicitud no encotrada.");

            var annosLaborados = DateTime.Now.Year - solicitud.Usuario.FechaIngreso.Year;
            if (solicitud.Usuario.FechaIngreso > DateTime.Now.AddYears(-annosLaborados)) annosLaborados--;

            return View(new SolicitudViewModel()
            {
                SolicitudId = solicitud.SolicitudVacacionesId,
                UsuarioId = solicitud.Usuario.Id,
                Nombre = solicitud.Usuario.Nombre,
                PrimerApellido = solicitud.Usuario.PrimerApellido,
                SegundoApellido = solicitud.Usuario.SegundoApellido,
                Email = solicitud.Usuario.Email,
                PhoneNumber = solicitud.Usuario.PhoneNumber,
                UnidadTecnica = solicitud.Usuario.UnidadTecnica,
                Categoria = solicitud.Usuario.Categoria,
                FechaIngreso = solicitud.Usuario.FechaIngreso,
                EstaActivo = solicitud.Usuario.EstaActivo,
                CantidadAnnosLaborados = annosLaborados < 0 ? 0 : annosLaborados,
                CantidadDiasSolicitados = solicitud.CantidadDiasSolicitados,
                Comentario = solicitud.Comentario,
                DiasPorSolicitud = solicitud.DiasPorSolicitud.Select(s => new DiasPorSolicitudViewModel()
                {
                    UsuarioId = s.UsuarioId,
                    Fecha = s.Fecha.ToString("yyyy-MM-dd"),
                    Periodo = s.Periodo
                }).ToList(),
                SaldoDiasDisponibles = solicitud.Usuario.SaldoDiasEmpleado.SaldoDiasDisponibles
            });
        }

        private string GeneratePDF(SolicitudViewModel solicitud)
        {
            var date = DateTime.Now.ToString("yyyyMMddHHmmss");
            var id = solicitud.Id;
            var fileName = $"{id}_{date}";

            var actionPDF = new Rotativa.ViewAsPdf("PDFView", solicitud)
            {
                PageSize = Rotativa.Options.Size.A4,
                PageOrientation = Rotativa.Options.Orientation.Portrait,
                PageMargins = new Margins(12, 12, 12, 12)
            };

CNMWebApp/Views/Solicitud/CrearParaEmpleado.cshtml
@model CNMWebApp.Models.SolicitudParaEmpleado

@{
    ViewBag.Title = "Crear a Nombre de un Colaborador";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Solicitar Vacaciones a nombre de un Colaborador</h2>

<hr />


@using (Html.BeginForm("CrearParaEmpleado", "Solicitud", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Colaboradores, "Colaborador", htmlAttributes: new { @id = "role-dropdown", @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.ColaboradorId, new SelectList(Model.Colaboradores, "Id", "NombreCompleto"), "- Seleccione un colaborador -", new { @class = "form-control selectpicker" })
                        @Html.ValidationMessageFor(model => model.ColaboradorId)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrimerApellido, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PrimerApellido, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.PrimerApellido, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SegundoApellido, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.SegundoApellido, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.SegundoApellido, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FechaIngresoEmpleado, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.FechaIngresoEmpleado, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.FechaIngresoEmpleado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CantidadAnnosLaborados, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CantidadAnnosLaborados, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.CantidadAnnosLaborados, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SaldoDiasDisponibles, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.SaldoDiasDisponibles, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.SaldoDiasDisponibles, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div hidden class="form-group">
                    @Html.LabelFor(model => model.Dias, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        <div class='input-group date datepicker-vacaciones'>
                            @Html.EditorFor(model => model.Dias, new { htmlAttributes = new { @type = "text", @class = "form-control" } })
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-th"></span>
                            </span>
                        </div>
                        @Html.ValidationMessageFor(model => model.Dias, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CantidadDiasSolicitados, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CantidadDiasSolicitados, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.CantidadDiasSolicitados, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        
        <div class="informacion-solicitud">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Dias, htmlAttributes: new { @class = "control-label" })
                            <div class="select-dates-empleado">
                                <input style="display: none;" id="selected-days" type="text" value="" readonly />
                            </div>
                            @Html.ValidationMessageFor(model => model.Dias, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Comentario, new { htmlAttributes = new { @class = "form-control", @cols = "1000" } })
                                @Html.ValidationMessageFor(model => model.Comentario, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <input type="submit" value="Solicitar" class="btn btn-default btn-block" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Regresar", "Index", "Home")
</div>

@section scripts
{
    <script>
        $('.select-dates-empleado').datepicker({
            format: 'yyyy/mm/dd',
            todayHighlight: true,
            multidate: true,
            linkField: 'Dias',
            linkFormat: 'yyyy/mm/dd',
            sideBySide: true,
            toolbarPlacement: 'bottom',
            showClear: true,
            startDate: new Date()
        }).datepicker();
        $('.select-dates-empleado').datepicker().on('changeDate', function (e) {
            var colaborador = $('#ColaboradorId').val();
            if (!colaborador) {
                $('.select-dates-empleado').datepicker('update', '');
                return;
            }

            var dias = $('#selected-days').val();
            $('#Dias').val(dias);

            $('#CantidadDiasSolicitados').val(e.dates.length);
        });

        $('#ColaboradorId').selectpicker({
            liveSearch: true,
            showSubtext: true,
            liveSearchPlaceholder: 'Buscar...'
        });

        $('#ColaboradorId').change(function (event) {
            var usuarioId = event.target.value;
            var url = '@Url.Action("ObtenerUsuarioPorId", "User")';

            if (!usuarioId) {
                $('#Id').val('');
                $('#Nombre').val('');
                $('#PrimerApellido').val('');
                $('#SegundoApellido').val('');
                $('#Email').val('');
                $('#PhoneNumber').val('');
                $('#FechaIngresoEmpleado').val('');
                $('#CantidadAnnosLaborados').val(0);
                $('#SaldoDiasDisponibles').val(0);
                $('#CantidadDiasSolicitados').val(0);
                $('.select-dates-empleado').datepicker('update', '');
                $('#Comentario').val('');
                return;
            }

            $.ajax({
                url: url,
                cache: false,
                data: { usuarioId: usuarioId },
                type: "GET",
                success: function (data) {
                    $('#Id').val(data.Usuario.Id);
                    $('#Nombre').val(data.Usuario.Nombre);
                    $('#PrimerApellido').val(data.Usuario.PrimerApellido);
                    $('#SegundoApellido').val(data.Usuario.SegundoApellido);
                    $('#Email').val(data.Usuario.Email);
                    $('#PhoneNumber').val(data.Usuario.PhoneNumber);
                    $('#FechaIngresoEmpleado').val(data.Usuario.FechaIngresoEmpleado);
                    $('#CantidadAnnosLaborados').val(data.Usuario.CantidadAnnosLaborados);
                    $('#SaldoDiasDisponibles').val(data.Usuario.SaldoDiasDisponibles);
                    $('#CantidadDiasSolicitados').val(data.Usuario.CantidadDiasSolicitados);
                },
                error: function (response) {
                    console.log(response.responseText);
                    alert("error : " + response.responseText);
                }
            });
        });

        var diasSeleccionados = $('#Dias').val();
        var array = diasSeleccionados.split(",");
        $('.select-dates-empleado').datepicker('setDates', array);
    </script>    
}

CNMWebApp/Views/Solicitud/Detalle.cshtml
@model CNMWebApp.Models.SolicitudViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Solicitud de Vacaciones</h2>

<h4>Detalle</h4>
<hr />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.SolicitudNumero, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.SolicitudNumero, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UsuarioId, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.UsuarioId, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrimerApellido, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PrimerApellido, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SegundoApellido, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.SegundoApellido, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.FechaIngreso, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CantidadAnnosLaborados, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CantidadAnnosLaborados, new { htmlAttributes = new { @class = "form-control", @readonly = "True" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SaldoDiasDisponibles, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.SaldoDiasDisponibles, new { htmlAttributes = new { @class = "form-control", @readonly = "True" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CantidadDiasSolicitados, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.CantidadDiasSolicitados, new { htmlAttributes = new { @class = "form-control", @readonly = "True" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Comentario, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Comentario, new { htmlAttributes = new { @class = "form-control", @readonly = "True" } })
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        @Html.Label("Días Solicitados", htmlAttributes: new { @class = "control-label" })
                        <div class="selected-dates">
                            <input style="display: none;" id="selected-days" type="text" value="" readonly />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Regresar", "Index", "Solicitud")
</div>

@section scripts
{
    <script>
        var diasPorSolicitud = @Html.Raw(Json.Encode(Model.DiasPorSolicitud));
        diasPorSolicitud = diasPorSolicitud.map(x => x.Fecha);

        $('.selected-dates').datepicker({
            format: 'yyyy/mm/dd',
            todayHighlight: true,
            multidate: true,
            beforeShowDay: function () {
                return false;
            }
        });

        $('.selected-dates').datepicker('setDates', diasPorSolicitud);
    </script>
}

CNMWebApp/Views/Solicitud/Detalles.cshtml
@model CNMWebApp.Models.SolicitudVacaciones

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>SolicitudVacaciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Estado.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario.FotoRuta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.FotoRuta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comentario)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SolicitudVacacionesId }) |
    @Html.ActionLink("Back to List", "Index")
</p>